name: Build WCM Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: martynrando/wcecoli
  RUNTIME_IMAGE: wcm-runtime
  WCM_IMAGE: wcm-full

jobs:
  build-runtime:
    name: Build runtime image
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Check out repository
        uses: action/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build runtime image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: cloud/docker/runtime/Dockerfile
          push: true
          build-args: |
            COMPILE_BLAS=0
            NO_AVX2=0
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.RUNTIME_IMAGE }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.RUNTIME_IMAGE }}:${{ github.sha }}
  build-wcm:
    name: Build WCM image (using runtime image)
    runs-on: ubuntu-latest
    needs: build-runtime

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out repository
        uses: action/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wcm image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: cloud/docker/wholecell/Dockerfile
          push: true
          build-args: |
            from=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.RUNTIME_IMAGE }}:latest
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.WCM_IMAGE }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.WCM_IMAGE }}:${{ github.sha }}
