name: Build webdocs image

on:
  push:
    branches: [ "20251204_webdocs" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: martynrando/wcecoli

jobs:
  build:
    name: Build webdocs docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build webdocs image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: cloud/docker/webdocs/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/wcm-webdocs:latest
